Use latest version of Jinja to fix build error
This fixes the error:

ImportError: cannot import name 'soft_unicode' from 'markupsafe'

Due to a breaking change in the markupsafe module. See
https://github.com/pallets/markupsafe/issues/284

I'm not entirely sure it's the *right* fix. It would probably be
better to pin our dependency versions.